#!/bin/sh

TESTURL='http://google.com'

if curl --output /dev/null --silent --head --fail "$TESTURL"; then
  echo "URL exists: $TESTURL"
else
  exit 1
fi

sudo /usr/bin/easy_install pip
sudo /usr/local/bin/pip install ansible
sudo /usr/local/bin/pip install markupsafe

rm /Library/LaunchDaemons/com.opera.intint.ansible_install.plist
rm -rf /usr/local/ansible_install

reboot
