#!/bin/bash

for i in {1..10};
do
  ping -q -c 1 google.com &> /dev/null
  if [ $? -eq 0 ]; then
    break
  else
    sleep 10
  fi
done

PATH=/usr/local/bin:$PATH

ansible-pull -U https://github.com/pearofducks/m -i localhost,


