#!/usr/bin/env ruby
gDir = File.expand_path "/gorilla"

ENV['BUNDLE_GEMFILE'] ||= gDir + "/Gemfile"
$:.unshift gDir

require 'bundler/setup'
require "keen"
require "dotenv"

# Dotenv.load

# k = Keen::Client.new(
#   project_id: ENV["PROJECT_ID"],
#   write_key: ENV["WRITE_KEY"],
# )

facts = `ansible all -m setup -i localhost, -c local`
f = File.open(Dir.home + "/foo","w")
f.puts facts
f.close

# k.publish( :mac,
#   {
#   var: value,
#   }
# )
