#!/usr/bin/ruby
gDir = File.expand_path "/gorilla"

ENV['BUNDLE_GEMFILE'] ||= gDir + "/Gemfile"
$:.unshift gDir

require 'bundler/setup'
require "keen"
require "dotenv"
require "facter"

Dotenv.load '/usr/local/.gorilla-env'

attributes = %w(fqdn id sp_machine_model processors sp_physical_memory sp_serial_number sp_os_version sp_uptime ipaddress macaddress timezone)
facts = {}

Facter.each do |k,v|
  if attributes.include? k
    facts[k] = v
  end
end
facts['disk'] = `df -h / | sed -n 2p`.strip
facts['encryption'] = `fdesetup status`.split(' ').last.strip

k = Keen::Client.new(
  project_id: ENV["PROJECT_ID"],
  write_key: ENV["WRITE_KEY"],
)

k.publish :heartbeat, facts
