#!/usr/bin/ruby
gDir = File.expand_path "/gorilla"

ENV['BUNDLE_GEMFILE'] ||= gDir + "/Gemfile"
$:.unshift gDir

require 'bundler/setup'
require "keen"
require "dotenv"
require "facter"

# TODO check encryption
attributes = %w(fqdn id sp_machine_model processors sp_physical_memory sp_serial_number sp_os_version sp_uptime ipaddress macaddress timezone)
facts = {}

Facter.each do |k,v|
  puts "#{k} :: #{v}"
  if attributes.include? k
    facts[k] = v
  end
end
facts['disk'] = `df -h / | sed -n 2p`.strip

puts facts
# Dotenv.load

# k = Keen::Client.new(
#   project_id: ENV["PROJECT_ID"],
#   write_key: ENV["WRITE_KEY"],
# )

# k.publish( :mac,
#   {
#   var: value,
#   }
# )
