---
- hosts: localhost
  connection: local
  tasks:
  - name: install gems
    gem: name={{ item }} state=latest
    environment:
      GEM_HOME: /gorilla
      GEM_PATH: /gorilla
    with_items:
    - keen
    - dotenv
  - name: copy heartbeat
    copy: src=./heartbeat dest=/gorilla/heartbeat mode=0755
  - name: run heartbeat
    shell: /gorilla/heartbeat
