---
- hosts: localhost
  connection: local
  tasks:
  - name: install gems
    gem: name={{ item }} state=latest executable=/usr/bin/gem
    with_items:
    - keen
    - dotenv
  - name: copy heartbeat
    copy: src=./heartbeat dest=/gorilla/heartbeat mode=0666
  - name: run heartbeat
    shell: /gorilla/heartbeat
