---
- hosts: localhost
  connection: local
  tasks:
  - name: make gorilla dir
    shell: mkdir /gorilla creates=/gorilla
  - name: copy gorilla files
    copy: src=./{{ item }} dest=/gorilla/{{ item }} mode=0755
    with_items:
    - Gemfile
    - Gemfile.lock
    - heartbeat
  - name: install bundler
    shell: /usr/bin/gem install -i /gorilla/bundler bundler creates=/gorilla/bundler
  - name: bundle gems
    shell: /gorilla/bundler/bin/bundle install --binstubs --jobs 4 --deployment --path gems
    args:
      chdir: /gorilla
      creates: /gorilla/gems
  - name: run heartbeat
    shell: /gorilla/heartbeat
    environment:
      GEM_HOME: /gorilla/bundler
