---
- hosts: localhost
  connection: local
  tasks:
  - name: copy gorilla files
    copy: src=./{{ item }} dest=/gorilla/{{ item }} mode=0755
    with_items:
    - Gemfile
    - Gemfile.lock
    - heartbeat
  - name: install bundler
    gem: name=bundler state=latest
  - name: bundle gems
    shell: bundle install --binstubs --jobs 4 --deployment --path gems
    args:
      chdir: /gorilla
      creates: /gorilla/gems
  - name: run heartbeat
    shell: /gorilla/heartbeat
