---
- tasks:
  - name: get gems
    gem: name=facter state=present executable=/usr/bin/gem
    gem: name=keen state=present executable=/usr/bin/gem
    gem: name=dotenv state=present executable=/usr/bin/gem
